/* groovylint-disable-next-line CompileStatic */
pipeline {
    agent {
        kubernetes {
            yaml '''
                apiVersion: v1
                kind: Pod
                metadata:
                    labels:
                        app: test
                spec:
                    containers:
                    - name: maven
                      image: maven:3.8.3-adoptopenjdk-11
                      command:
                      - cat
                      tty: true
                    - name: git
                      image: "bitnami/git:latest"
                      command:
                      - cat
                      tty: true
            '''
        }
    }

    stages {
        stage('Hello') {
            steps {
                container('maven') {
                    sh 'mvn -version'
                }
            }
        }
    }
}
