apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flaskapp-deployment
spec:
  selector:
    matchLabels:
      app: my-flaskapp
  template:
    metadata:
      labels:
        app: my-flaskapp
    spec:
      containers:
      - name: my-flaskapp
        image: registry.digitalocean.com/lab-image-registry/my-flaskapp
        ports:
        - containerPort: 5000
