apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: default
spec:
  selector: 
    app: jenkins-server
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
      
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
  namespace: default
spec:
  selector: 
    app: jenkins-server
  type: ClusterIP  
  ports:
    - port: 50000
      targetPort: 50000
   